/* =============================================================
   CHAT — Conversation rendering and question submission
   ============================================================= */

const ResumeChat = (function () {

    let history;
    let form;
    let input;
    let sendButton;
    let emptyState;
    let contextList;
    let isResumeReady = false;

    function formatTimestamp(date) {
        return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    }

    function scrollToLatest() {
        history.scrollTop = history.scrollHeight;
    }

    function clearEmptyState() {
        if (emptyState && emptyState.parentElement) {
            emptyState.remove();
        }
    }

    function appendMessage(role, text) {
        clearEmptyState();

        const message = document.createElement("article");
        message.className = `chat-message chat-message--${role}`;

        const bubble = document.createElement("div");
        bubble.className = "chat-message-bubble";
        // Markdown-ready container: paragraphs are split on blank lines.
        text.split(/\n{2,}/).forEach((paragraph) => {
            const p = document.createElement("p");
            p.textContent = paragraph;
            bubble.appendChild(p);
        });

        const timestamp = document.createElement("time");
        timestamp.className = "chat-message-timestamp";
        timestamp.textContent = formatTimestamp(new Date());

        message.appendChild(bubble);
        message.appendChild(timestamp);
        history.appendChild(message);
        scrollToLatest();
    }

    function showTypingIndicator() {
        const indicator = document.createElement("div");
        indicator.className = "chat-typing-indicator";
        indicator.setAttribute("aria-label", "Assistant is typing");
        indicator.innerHTML = "<span></span><span></span><span></span>";
        history.appendChild(indicator);
        scrollToLatest();
        return indicator;
    }

    function renderRetrievedContext(chunks) {
        if (!contextList) return;
        contextList.innerHTML = "";

        if (!chunks || chunks.length === 0) {
            const empty = document.createElement("p");
            empty.className = "retrieved-context-empty";
            empty.textContent = "No supporting passages were retrieved for this answer.";
            contextList.appendChild(empty);
            return;
        }

        chunks.forEach((chunk, index) => {
            const card = document.createElement("details");
            card.className = "retrieval-chunk-card";

            const score = document.createElement("span");
            score.className = "retrieval-chunk-score";
            score.textContent = `${Math.round((chunk.score || 0) * 100)}% match`;

            const summary = document.createElement("summary");
            summary.className = "retrieval-chunk-summary";
            const chunkIndex = document.createElement("span");
            chunkIndex.className = "retrieval-chunk-index";
            chunkIndex.textContent = `Chunk ${String(index + 1).padStart(2, "0")}`;
            const preview = document.createTextNode(
                " — " + chunk.chunk.slice(0, 72) + (chunk.chunk.length > 72 ? "…" : "")
            );
            summary.appendChild(chunkIndex);
            summary.appendChild(preview);

            const fullText = document.createElement("p");
            fullText.className = "retrieval-chunk-text";
            fullText.textContent = chunk.chunk;

            card.appendChild(score);
            card.appendChild(summary);
            card.appendChild(fullText);
            contextList.appendChild(card);
        });
    }

    /**
     * Local fallback used only when the backend is unreachable, so the
     * chat panel and retrieval panel remain demonstrable standalone.
     */
    function simulateAnswer(question) {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    answer: `Here's what the uploaded resume shows related to "${question}". Once connected to the live backend, this response will be generated by the RAG pipeline over your actual document.`,
                    context: [
                        { chunk: "5 years of experience building distributed systems in Go and Python, leading a team of four engineers.", score: 0.91 },
                        { chunk: "Led migration of the payments platform to an event-driven architecture, reducing latency by 38%.", score: 0.84 },
                        { chunk: "B.Sc. in Computer Science, graduated with honors, relevant coursework in machine learning.", score: 0.67 }
                    ]
                });
            }, 900);
        });
    }

    async function handleSubmit(event) {
        event.preventDefault();
        const question = input.value.trim();
        if (!question) return;

        appendMessage("user", question);
        input.value = "";
        input.style.height = "auto";
        sendButton.disabled = true;

        const typingIndicator = showTypingIndicator();

        try {
            let result;
            try {
                result = await ResumeRagApi.askQuestion(question);
            } catch (networkError) {
                result = await simulateAnswer(question);
            }

            typingIndicator.remove();
            appendMessage("assistant", result.answer || "No answer was returned.");

            if (result.context) {
               renderRetrievedContext(result.context);
}
        } catch (error) {
            typingIndicator.remove();
            appendMessage("assistant", "I couldn't reach the resume assistant. Please try again in a moment.");
        } finally {
            sendButton.disabled = false;
            input.focus();
        }
    }

    function autoGrowInput() {
        input.style.height = "auto";
        input.style.height = `${Math.min(input.scrollHeight, 160)}px`;
    }

    function setResumeReady(ready) {
        isResumeReady = ready;
        if (input) {
            input.placeholder = ready
                ? "Ask anything about your resume…"
                : "Upload a resume to start asking questions…";
        }

        const statusPill = document.querySelector("[data-chat-status]");
        if (statusPill) {
            statusPill.textContent = ready ? "Resume ready" : "Awaiting resume";
            statusPill.className = `status-pill ${ready ? "status-pill--complete" : "status-pill--pending"}`;
            statusPill.setAttribute("data-chat-status", "");
        }
    }

    function attachEvents() {
        form.addEventListener("submit", handleSubmit);

        input.addEventListener("keydown", (event) => {
            if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                form.requestSubmit();
            }
        });

        input.addEventListener("input", autoGrowInput);
    }

    function init() {
        history = document.querySelector(".chat-message-history");
        form = document.querySelector(".chat-input-area");
        input = document.querySelector(".chat-input-field");
        sendButton = document.querySelector(".send-question-button");
        emptyState = document.querySelector(".chat-empty-state");
        contextList = document.querySelector(".retrieved-context-list");

        if (!history || !form || !input) return;

        setResumeReady(false);
        attachEvents();
    }

    return { init, setResumeReady, appendMessage };

})();

window.ResumeChat = ResumeChat;
